### ISSUE TITLE
Freeze on extracting 

### ISSUE THREAD

**Issue by marshfire** [pchorus/grunt-angular-translate-extract#5]
In html the following currently freezes the extraction:

`  <md-button class="orca-menu-opener md-icon-button" aria-label="{{'Open {name}' | translate:{name:name} }}" ng-click="$mdOpenMenu($event)"
    ng-disabled="isMenuDisabled()">
`

happend with 0.4.4, earlier versions did work on that, though I cant say which (whatever was current on Nov, 22 still worked)

update: 0.4.2 still works, 0.4.3 doesn't

**Comment by pchorus** [comment]
Hi @marshfire,
I tried to reproduce this issue, but it works fine for me. Could you please provide your original file containing the string you provided above?

I added a unit test containing this md-button tag and it extracts 'Open {name}' as expected.
