### ISSUE TITLE
Extract not working on pug-files

### ISSUE THREAD

**Issue by olehmach** [pchorus/grunt-angular-translate-extract#6]
`label="'Beschaffungslogistik aktiv' | translate` is not extracted  in .pug-files

If I change it to `label="{{ 'Beschaffungslogistik aktiv' | translate }}` the extraction process works, however this is not a valid angular parameter.

**Comment by pchorus** [comment]
Could you please provide an example file or a sample jsfiddle/plunker?

**Comment by olehmach** [comment]
`.plant-list
    div.plantRow(ng-repeat='plant in vm.items.Items', plant-list-row, entry='plant',
    on-select-command='vm.OnClick', on-delete-command='vm.OnDeleteClick')
    io-select.addPlantDropDown(
    ng-if='vm._itemEditActive',
    ng-cloak,
    models="vm.unusedItems",
    placeholder="'bitte wählen' | translate",
    on-selection-change='vm.createNewPlant',
    filter-enabled="true",
    alignment="both")
`

**Comment by pchorus** [comment]
I created a fixture pug file for unit tests. Here it is:
```
div(translate="Directive, text in attribute")
div(translate="translate text")

div(translate, translate-interpolation="messageformat" translate-values="{NAME: name}") translate messageformat
div(translate ng-if="{ count > index }" ng-class='{green: count > index }') translate > " < ' if non greedy please!
div(translate ng-class="{ green: count > index}") translate ng-class

div(translate) Directive, text in element's content

div(placeholder="{{ 'Filter' | translate }}")

div {{ 'Filter' | translate }}

div [[ 'Filter custom interpolation' | translate ]]

md-button(class="orca-menu-opener md-icon-button" aria-label="{{'Open {name}' | translate:{name:name} }}" ng-click="$mdOpenMenu($event)" ng-disabled="isMenuDisabled()")
```

For attributes, I used {{ and }} to mask the expression containing the translate filter. This perfectly compiles to the desired output.
Example: Line
```
div(placeholder="{{ 'Filter' | translate }}")
```
compiles to
```
<div placeholder="{{ 'Filter' | translate }}"></div>
```
That is exactly what I expected as the correct output.
Am I missing something here?
Please tell me if the other lines in the pug file are correct since I don't have any experience with pug.

**Comment by olehmach** [comment]
The problem is, that  
`<div placeholder="{{ 'Filter' | translate }}"></div>`
is not a valid usage of an attribute. 
It it gives the following error:  
![image](https://user-images.githubusercontent.com/6881750/34763178-7dd3829e-f5ea-11e7-94cb-5f50e0f8d524.png)

**Comment by pchorus** [comment]
Please check out the following plunker: https://plnkr.co/edit/WoCkLkaY4muBKMIAaNv6
`<input placeholder="{{ 'TRANSLATION_ID' | translate }}">` is working exactly as expected. So I still don't see your problem.

**Comment by pchorus** [comment]
Any news on this issue?

**Comment by pchorus** [comment]
Since I get no new information on this issue, I close it now.
If there is still any problem, please reopen.
